GET http://localhost:3000/places?text=av nevada 645, santo andré,sp 

###
GET http://localhost:3000/places?text=rua carneiro leão, santo andré,sp 


###

@originId = ChIJXT005w9ozpQRJII6yB2GaMU
@destinationId = ChIJkTL2ClpCzpQRxdNcd7CJjag

GET http://localhost:3000/directions?originId={{originId}}&destinationId={{destinationId}}

###

POST http://localhost:3000/routes
Content-Type: application/json

{
    "name" :"teste 2",
    "source_id": "{{originId}}",
    "destination_id": "{{destinationId}}"
}


###
GET http://localhost:3000/routes


###

GET http://localhost:3000/routes/675863d772332095b975be91
